### ISSUE TITLE
dependency on retiring spatial infrastructure packages

### ISSUE THREAD

**Issue by rsbivand** [dlaydon/DivE#1]
You will be aware, for example from:
https://r-spatial.org/r/2022/04/12/evolution.html,
https://r-spatial.org/r/2022/12/14/evolution2.html,
https://r-spatial.org/r/2023/04/10/evolution3.html and
https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and 
perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1 
that `rgdal`, `rgeos` and `maptools` will be retired this
year, in October 2023. 

DivE depends on `rgeos`. NAMESPACE shows a bulk import of `rgeos`, `pkgapi` only finds use of `rgeos::gIntersection`. This is at line 316 in R/DivE.R. It looks as though the spatial objects are used simply because that is what `rgeos` takes, so another topology package, such as `geos` - to keep GEOS - may be feasible, with custom construction of objects (to avoid requiring `sf`). Action is needed best by June, latest by October 2023.

**Comment by rsbivand** [comment]
Only three months remain to keep this package online on CRAN. Please act now!

**Comment by rsbivand** [comment]
@dlaydon Less than three weeks remain to fix this.

**Comment by rsbivand** [comment]
@dlaydon R spatial infrastructure packages maptools, rgdal and rgeos will be archived by CRAN on Monday, October 16, 2023. Your package does not pass CMD check when these packages are not available. Expect your package to be archived by CRAN October 17-18 as CRAN checks feed through and your package fails, if not updated by Monday, October 16, 2023. 

No grace period is anticipated, as you have had sufficient time to update your package to remove dependencies on maptools, rgdal and/or rgeos.

**Comment by dlaydon** [comment]
Hi @rsbivand I've just uploaded revised DivE package to CRAN. Hopefully this wil address the issue you've raised. Thank you for bringing it to my attention.

**Comment by dlaydon** [comment]
Closing issue now.

**Comment by rsbivand** [comment]
Thanks for your cooperation!
